-- =====================================================================
-- 0021 — Full developer coverage (broker master list)
--
-- Encodes the owner's authoritative villa/townhouse list: 7 new developers,
-- 20 new master communities and 317 sub-community/cluster rows across every
-- major developer (Emaar, DAMAC, Nakheel, Dubai Holding/Meraas/Wasl, Meydan/
-- Sobha/MBR City, MAF, Aldar, Azizi, Nshama + niche/island/podium projects).
--
-- Structural registry only; data_confidence='high' (broker-validated);
-- no invented prices/counts; idempotent upsert. This is the USP breadth:
-- every villa/TH community in Dubai, organised by developer.
-- =====================================================================

-- New developers -------------------------------------------------------
insert into developers (name, slug) values
  ('H&H Development','hh-development'),
  ('MAG','mag'),
  ('G&Co Properties','g-and-co'),
  ('Expo City Dubai','expo-city-dubai'),
  ('Dubai Silicon Oasis Authority','dsoa'),
  ('Amali Properties','amali'),
  ('Kleindienst Group','kleindienst')
on conflict (slug) do nothing;

-- New master communities ----------------------------------------------
insert into communities
  (slug, developer_id, name, status, positioning_tier,
   age_or_handover, description_long, who_its_for_base, character_tags,
   is_placeholder, data_confidence, source_note)
select v.slug, (select id from developers where slug=v.dev), v.name,
       v.status::status_tag, v.tier::positioning_tier,
       v.age, v.descr, v.who, v.tags::text[], false, 'high', v.note
from (values
  ('the-heights-country-club','emaar','The Heights Country Club & Wellness','offplan','premium','Off-plan','Emaar wellness-themed townhouse & twin-villa community in deep Dubailand (Serro, Grandio, Faro) around a country club.','Wellness-minded families wanting a new Emaar townhouse/villa with a country-club lifestyle.','{new-launch,gated-family,wellness,nature}','Broker-provided master list (validated), Jul 2026.'),
  ('sur-la-mer','meraas','Sur La Mer (Port de La Mer)','ready','prime','Ready','Meraas waterfront townhouse enclave at Port de La Mer, Jumeirah — multi-level marine townhouses with roof decks.','Buyers wanting a beachfront townhouse minutes from the city with a marina lifestyle.','{waterfront,beach,prestige,central}','Broker-provided master list (validated), Jul 2026.'),
  ('dar-wasl','wasl','Dar Wasl','ready','prime','Ready','Upscale wasl Andalusian-style villa/townhouse compound on Al Wasl Road, Jumeirah.','Families wanting a central, gated Andalusian villa near Jumeirah and Downtown.','{central,gated-family,prestige}','Broker-provided master list (validated), Jul 2026.'),
  ('wasl-51','wasl','Wasl 51','ready','premium','Ready','wasl urban townhouses at Jumeirah 1 integrated with a high-end retail strip.','Buyers wanting a central townhouse with retail at the door in Jumeirah.','{central,gated-family}','Broker-provided master list (validated), Jul 2026.'),
  ('wasl-square','wasl','Wasl Square','ready','premium','Ready','wasl townhouse cluster beside Safa Park, Al Safa.','Families wanting a central townhouse next to Safa Park.','{central,gated-family,schools-nearby}','Broker-provided master list (validated), Jul 2026.'),
  ('shorooq','dubai-holding','Shorooq','ready','mid','Ready','Dubai Holding gated Mirdif enclave of standalone villas and townhouse rows.','Families wanting an affordable, established villa/townhouse near Mirdif schools.','{established,gated-family,schools-nearby}','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-sanctuary','sobha','The Willows at Sobha Sanctuary','offplan','ultra_prime','Off-plan','Sobha "The Willows" villa collection at Sobha Sanctuary, Nad Al Sheba (The Brooks, The Grove, The Greens).','Buyers wanting a new, high-quality Sobha villa in a green Nad Al Sheba setting.','{new-launch,gated-family,nature,prestige}','Broker-provided master list (validated), Jul 2026.'),
  ('eden-hills','hh-development','Eden Hills','offplan','ultra_prime','Off-plan','H&H Development gated MBR-area community of 350 ultra-luxury 5–6BR villas along a natural wadi.','UHNW buyers wanting a bespoke villa along a natural wadi in a boutique gated community.','{new-launch,ultra-luxury,nature,prestige}','Broker-provided master list (validated), Jul 2026.'),
  ('the-sanctuary-ellington','ellington','The Sanctuary by Ellington','offplan','prime','Off-plan','Ellington boutique villa community in District 11 (Waterside, Lakeshore, Beachfront, Lakeview) — design-led 4–6BR villas.','Design-conscious buyers wanting a boutique, lakeside Ellington villa.','{new-launch,gated-family,waterfront,prestige}','Broker-provided master list (validated), Jul 2026.'),
  ('opal-gardens','meydan','Opal Gardens (District 11)','offplan','prime','Off-plan','Meydan/Nakheel JV gated community in District 11 of semi-detached and standalone lakeside villas.','Families wanting a gated lakeside villa in central MBR City.','{new-launch,gated-family,waterfront,central}','Broker-provided master list (validated), Jul 2026.'),
  ('keturah-reserve','mag','Keturah Reserve','offplan','ultra_prime','Off-plan','MAG bio-living luxury gated wellness community in MBR District 7 of interconnected townhouses in raw travertine.','Wellness-focused UHNW buyers wanting a design-forward, central townhouse.','{new-launch,ultra-luxury,wellness,central}','Broker-provided master list (validated), Jul 2026.'),
  ('mag-city','mag','MAG City','ready','mid','Ready','MAG entry-to-mid compact urban townhouses in MBR District 7 (MAG Eye).','Value buyers wanting an affordable, central new townhouse.','{gated-family,central,investment}','Broker-provided master list (validated), Jul 2026.'),
  ('the-fields','g-and-co','The Fields at MBR City','ready','premium','Ready','G&Co gated townhouse community at MBR City (Cassia, Jade, Viridian, Senses by Elie Saab).','Families wanting a modern, central attached townhouse with design pedigree.','{gated-family,central,schools-nearby}','Broker-provided master list (validated), Jul 2026.'),
  ('ghaf-woods','majid-al-futtaim','Ghaf Woods','offplan','premium','Off-plan','Majid Al Futtaim biophilic forest community — multi-tier forest townhouses among thousands of trees.','Nature-led families wanting a forest-immersed new townhouse from MAF.','{new-launch,gated-family,nature,wellness}','Broker-provided master list (validated), Jul 2026.'),
  ('expo-city','expo-city-dubai','Expo City Dubai','offplan','premium','Off-plan','Expo City Dubai eco townhouse/villa community (Expo Valley, Shamsa, Yasmina) on the Expo legacy site.','Sustainability-minded families wanting a new eco villa/townhouse near Expo/airport.','{new-launch,gated-family,wellness,nature}','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-silicon-oasis','dsoa','Dubai Silicon Oasis','ready','mid','Ready','DSO established detached villa compounds (Cedre Villas, Semmer Villas) — spacious legacy family homes.','Families wanting a spacious, affordable established villa in a tech-hub district.','{established,gated-family,schools-nearby}','Broker-provided master list (validated), Jul 2026.'),
  ('amali-island','amali','Amali Island','offplan','ultra_prime','Off-plan','Amali Properties: 24 ultra-exclusive beachfront mansions on The World Islands with private berths.','UHNW buyers wanting a private-island beachfront mansion.','{new-launch,ultra-luxury,waterfront,beach,prestige}','Broker-provided master list (validated), Jul 2026.'),
  ('the-world-islands','kleindienst','The World Islands (Heart of Europe)','mixed','ultra_prime','Mixed','Kleindienst "Heart of Europe" island villa collection (Germany, Sweden, Floating Seahorse).','UHNW buyers wanting a themed private-island beach estate.','{ultra-luxury,waterfront,beach,prestige}','Broker-provided master list (validated), Jul 2026.'),
  ('rashid-yachts-marina','emaar','Rashid Yachts & Marina','offplan','prime','Off-plan','Emaar Mina Rashid waterfront podium townhouses (Seascape, Sunridge, Sirius) over the yacht basin.','Buyers wanting a waterfront townhouse on a mega-yacht marina near the city.','{new-launch,waterfront,central,investment}','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-creek-harbour','emaar','Dubai Creek Harbour','mixed','prime','Mixed','Emaar Creek Harbour podium townhouses (Creek Beach, Creek Waters) at the base of waterfront towers.','Buyers wanting a rare waterfront townhouse in a prime creekside district.','{waterfront,central,investment}','Broker-provided master list (validated), Jul 2026.')
) as v(slug, dev, name, status, tier, age, descr, who, tags, note)
on conflict (slug) do update set
  age_or_handover=excluded.age_or_handover, description_long=excluded.description_long,
  who_its_for_base=excluded.who_its_for_base, character_tags=excluded.character_tags,
  is_placeholder=false, data_confidence=excluded.data_confidence, source_note=excluded.source_note;

-- New sub-communities / clusters --------------------------------------
insert into sub_communities
  (community_id, slug, name, status, is_placeholder, data_confidence, source_note)
select (select id from communities where slug=v.comm), v.slug, v.name, v.status::status_tag,
       true, 'high', v.note
from (values
  ('grand-polo-club','chevalia-estate','Chevalia Estate','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('grand-polo-club','chevalia-fields','Chevalia Fields','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('grand-polo-club','selvara','Selvara','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('grand-polo-club','selvara-2','Selvara 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('grand-polo-club','selvara-4','Selvara 4','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-oasis','palmiera-2','Palmiera 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-oasis','mareva','Mareva','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-oasis','mareva-2','Mareva 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-oasis','tierra','Tierra','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-oasis','address-villas-oasis','Address Villas Oasis','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-oasis','ostra-palace','Ostra Palace','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-heights-country-club','serro','Serro','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('the-heights-country-club','serro-2','Serro 2','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('the-heights-country-club','grandio','Grandio','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('the-heights-country-club','faro','Faro','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','talia','Talia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','orania','Orania','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','elora','Elora','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','farm-gardens-2','Farm Gardens 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','nima','Nima','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','lillia','Lillia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','venera','Venera','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','virella','Virella','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','vindera','Vindera','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','avena','Avena','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','avena-2','Avena 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','farm-grove','Farm Grove','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','farm-grove-2','Farm Grove 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','elea','Elea','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','elva','Elva','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','kaia','Kaia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','ovelle','Ovelle','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','avelia','Avelia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-valley','alva','Alva','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','sidra-1','Sidra 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','sidra-2','Sidra 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','sidra-3','Sidra 3','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','maple-1','Maple 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','maple-2','Maple 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','maple-3','Maple 3','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','golf-place-i','Golf Place I','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','golf-place-ii','Golf Place II','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','hills-grove','Hills Grove','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','hills-view','Hills View','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','lime-gardens','Lime Gardens','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','park-gate','Park Gate','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-hills-estate','park-gate-phase-2','Park Gate Phase 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches','al-mahra','Al Mahra','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches','san-luis','San Luis','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches','santa-fe','Santa Fe','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches','polo-homes','Polo Homes','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-2','casa','Casa','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-2','rasha','Rasha','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-2','samara','Samara','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-2','yasmin','Yasmin','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-2','reem-townhouses','Reem Townhouses','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-3','spring','Spring','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-3','bliss-2','Bliss 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-3','anya-2','Anya 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-3','raya','Raya','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-3','elie-saab-ii','Elie Saab II','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-3','june','June','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-3','june-ii','June II','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-3','idyllic','Idyllic','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('arabian-ranches-3','may','May','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('emaar-south','urbana-i','Urbana I','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('emaar-south','urbana-ii','Urbana II','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('emaar-south','urbana-iii','Urbana III','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('emaar-south','greenwood','Greenwood','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('emaar-south','fairways','Fairways','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('emaar-south','saffron','Saffron','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('emaar-south','golf-fields','Golf Fields','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('emaar-south','golf-vale','Golf Vale','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('emaar-south','parkside','Parkside','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','trump-estates','Trump Estates','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','gems-estates','Gems Estates','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','cavalli-estates','Cavalli Estates','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','utopia','Utopia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','fendi-styled-villas','Fendi Styled Villas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','paramount-villas','Paramount Villas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','belair','Belair','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','veneto','Veneto','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','queens-meadows','Queens Meadows','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','brookfield','Brookfield','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','trinity','Trinity','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','richmond','Richmond','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','loreto','Loreto','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','orchid','Orchid','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','topanga','Topanga','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','pelham','Pelham','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','piccadilly-green','Piccadilly Green','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','rochester','Rochester','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills','jasmine','Jasmine','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','aster','Aster','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','basswood','Basswood','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','camelia','Camelia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','claret','Claret','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','coursetia','Coursetia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','danusia','Danusia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','dynamic','Dynamic','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','eton','Eton','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','forenous','Forenous','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','ghaf-trees','Ghaf Trees','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','janusia','Janusia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','juniper','Juniper','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','mimosa','Mimosa','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','mulberry','Mulberry','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','odora','Odora','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','pacifica','Pacifica','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','primrose','Primrose','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','rawda','Rawda','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','santini','Santini','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','sycamore','Sycamore','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','trixis','Trixis','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','vardon','Vardon','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','zinnia','Zinnia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','park-greens','Park Greens','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','violet-1','Violet 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','violet-2','Violet 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','violet-3','Violet 3','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','violet-4','Violet 4','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-hills-2','elo-townhouses','Elo Townhouses','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-lagoons','marbella','Marbella','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-lagoons','marbella-2','Marbella 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-lagoons','mykonos','Mykonos','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-lagoons','monte-carlo','Monte Carlo','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-lagoons','ibiza','Ibiza','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-lagoons','venice-2','Venice 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-riverside','rome','Rome','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-riverside','paris','Paris','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-riverside','london','London','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-riverside','amsterdam','Amsterdam','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-riverside','new-york','New York','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-islands','bahamas','Bahamas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-islands','fiji','Fiji','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-islands','bora-bora','Bora Bora','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-sun-city','phase-1','Phase 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('damac-sun-city','phase-2','Phase 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('palm-jumeirah','palma-residences','Palma Residences','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('palm-jumeirah','balqis-residences','Balqis Residences','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('palm-jumeirah','xxii-carat','XXII Carat','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('palm-jumeirah','kingdom-of-sheba','Kingdom of Sheba','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('palm-jumeirah','six-senses-residences','Six Senses Residences','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('palm-jumeirah','orla','Orla','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('palm-jumeirah','ava','Ava','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-islands','waterfront-villas','Waterfront Villas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-park','jumeirah-park-homes','Jumeirah Park Homes','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-islands','islamic-clusters','Islamic Clusters','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-islands','mansions','Mansions','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-islands','jumeirah-islands-townhouses','Jumeirah Islands Townhouses','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('al-furjan','al-furjan-west','Al Furjan West','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('al-furjan','al-furjan-east','Al Furjan East','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('al-furjan','murooj-al-furjan','Murooj Al Furjan','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('al-furjan','murooj-al-furjan-west','Murooj Al Furjan West','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('al-furjan','dreamz-by-danube','Dreamz by Danube','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('nad-al-sheba-villas','nad-al-sheba-1','Nad Al Sheba 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('nad-al-sheba-villas','nad-al-sheba-2','Nad Al Sheba 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('nad-al-sheba-villas','nad-al-sheba-4','Nad Al Sheba 4','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-triangle','jvt-district-2','JVT District 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-triangle','jvt-district-3','JVT District 3','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-triangle','jvt-district-5','JVT District 5','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-triangle','jvt-district-6','JVT District 6','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-triangle','jvt-district-8','JVT District 8','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-triangle','jvt-district-9','JVT District 9','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-circle','jvc-district-11','JVC District 11','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-circle','jvc-district-12','JVC District 12','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-circle','jvc-district-13','JVC District 13','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-circle','jvc-district-14','JVC District 14','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-circle','jvc-district-15','JVC District 15','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-circle','jvc-district-16','JVC District 16','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-village-circle','eleganz-by-danube','Eleganz by Danube','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('mudon','rahat','Rahat','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('mudon','naseem','Naseem','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('mudon','arabella-1','Arabella 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('mudon','arabella-2','Arabella 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('mudon','arabella-3','Arabella 3','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','amaranta-1','Amaranta 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','amaranta-2','Amaranta 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','amaranta-3','Amaranta 3','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','amaranta-4','Amaranta 4','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','la-rosa-1','La Rosa 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','la-rosa-2','La Rosa 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','la-rosa-3','La Rosa 3','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','la-rosa-4','La Rosa 4','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','la-rosa-5','La Rosa 5','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','la-rosa-6','La Rosa 6','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','la-violeta-1','La Violeta 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villanova','la-violeta-2','La Violeta 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-villa','the-aldea','The Aldea','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-villa','the-centro','The Centro','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-villa','the-haciendas','The Haciendas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-acres','phase-1','Phase 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-acres','phase-2','Phase 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-bay-island','bulgari-villas','Bulgari Villas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-bay-island','sea-mirror-mansions','Sea Mirror Mansions','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('wasl-gate','gardenia-townhomes-i','Gardenia Townhomes I','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('wasl-gate','gardenia-townhomes-ii','Gardenia Townhomes II','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('district-one','phase-1','Phase 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('district-one','phase-2','Phase 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('district-one','phase-3','Phase 3','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('district-one','phase-4','Phase 4','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('district-one','district-one-west-1','District One West 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('district-one','district-one-west-2','District One West 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-hartland','water-canal-villas','Water Canal Villas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-hartland','gardenia-villas','Gardenia Villas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-hartland','quad-homes','Quad Homes','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-hartland-2','sobha-mansions','Sobha Mansions','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-hartland-2','hartland-ii-villas-phase-1','Hartland II Villas Phase 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-hartland-2','hartland-ii-villas-phase-2','Hartland II Villas Phase 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-hartland-2','hartland-ii-villas-phase-3','Hartland II Villas Phase 3','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-elwood','elwood-phase-1','Elwood Phase 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-elwood','elwood-phase-2','Elwood Phase 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-sanctuary','the-brooks','The Brooks','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-sanctuary','the-grove','The Grove','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('sobha-sanctuary','the-greens','The Greens','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('eden-hills','edra','Edra','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('eden-hills','maia','Maia','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('eden-hills','avra','Avra','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('eden-hills','aurora','Aurora','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('eden-hills','vera','Vera','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('eden-hills','mira','Mira','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('eden-hills','luna','Luna','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('the-sanctuary-ellington','the-waterside','The Waterside','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('the-sanctuary-ellington','the-lakeshore','The Lakeshore','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('the-sanctuary-ellington','the-beachfront','The Beachfront','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('the-sanctuary-ellington','the-lakeview','The Lakeview','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('the-fields','cassia','Cassia','ready','Broker-provided master list (validated), Jul 2026.'),
  ('the-fields','jade','Jade','ready','Broker-provided master list (validated), Jul 2026.'),
  ('the-fields','viridian','Viridian','ready','Broker-provided master list (validated), Jul 2026.'),
  ('the-fields','senses','Senses','ready','Broker-provided master list (validated), Jul 2026.'),
  ('meydan-gardens','grand-views','Grand Views','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('meydan-gardens','polo-townhouses','Polo Townhouses','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('meydan-gardens','polo-residences','Polo Residences','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('tilal-al-ghaf','aura','Aura','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('tilal-al-ghaf','alaya-gardens','Alaya Gardens','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('tilal-al-ghaf','elysian-mansions','Elysian Mansions','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('tilal-al-ghaf','lanai-islands','Lanai Islands','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('tilal-al-ghaf','serenity-mansions','Serenity Mansions','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('haven-by-aldar','oasis-villas','Oasis Villas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('haven-by-aldar','falls-townhouses','Falls Townhouses','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('haven-by-aldar','glade-townhouses','Glade Townhouses','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('haven-by-aldar','ferns-townhouses','Ferns Townhouses','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('azizi-venice','venice-villas','Venice Villas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('azizi-venice','waterfront-mansions','Waterfront Mansions','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('azizi-venice','sky-villas','Sky Villas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('town-square','safi','Safi','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('town-square','noor','Noor','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('town-square','sama','Sama','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('town-square','maha','Maha','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('town-square','reem','Reem','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('town-square','alton','Alton','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('town-square','rosewell','Rosewell','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('al-barari','jasmine','Jasmine','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('al-barari','desert-leaf','Desert Leaf','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('al-barari','silk-leaf','Silk Leaf','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('al-barari','bromellia','Bromellia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('al-barari','camellia','Camellia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('al-barari','lunaria','Lunaria','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','whispering-pines','Whispering Pines','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','flame-tree-ridge','Flame Tree Ridge','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','wildflower','Wildflower','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','sanctuary-falls','Sanctuary Falls','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','olive-point','Olive Point','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','sienna-lakes','Sienna Lakes','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','sienna-views','Sienna Views','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','lime-tree-valley','Lime Tree Valley','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','jumeirah-luxury','Jumeirah Luxury','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','redwood-avenue','Redwood Avenue','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','redwood-villas','Redwood Villas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','terra-golf-collection','Terra Golf Collection','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('jumeirah-golf-estates','jouri-hills-by-arada','Jouri Hills by Arada','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('victory-heights','olivia','Olivia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('victory-heights','calida','Calida','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('victory-heights','carmen','Carmen','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('victory-heights','fortuna','Fortuna','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('victory-heights','marbella','Marbella','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('green-community-motor-city','casa-flores','Casa Flores','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-pulse','south-village','South Village','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('falcon-city','western-autograph','Western Autograph','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('falcon-city','aegean','Aegean','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('falcon-city','andalusia','Andalusia','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('falcon-city','new-world','New World','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('falcon-city','santa-fe','Santa Fe','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-sustainable-city','cluster-1','Cluster 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-sustainable-city','cluster-2','Cluster 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-sustainable-city','cluster-3','Cluster 3','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-sustainable-city','cluster-4','Cluster 4','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-sustainable-city','cluster-5','Cluster 5','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('rukan','rukan-villas','Rukan Villas','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('rukan','bianca-townhouses','Bianca Townhouses','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('living-legends','type-a','Type A','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('living-legends','type-b','Type B','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('living-legends','type-c','Type C','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('living-legends','type-d','Type D','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('living-legends','type-e','Type E','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villa-lantana','villa-lantana-1','Villa Lantana 1','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('villa-lantana','villa-lantana-2','Villa Lantana 2','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('expo-city','expo-valley','Expo Valley','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('expo-city','shamsa-townhouses','Shamsa Townhouses','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('expo-city','yasmina-villas','Yasmina Villas','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-silicon-oasis','cedre-villas-dso','Cedre Villas DSO','ready','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-silicon-oasis','semmer-villas','Semmer Villas','ready','Broker-provided master list (validated), Jul 2026.'),
  ('amali-island','avatea','Avatea','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('amali-island','aria','Aria','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('amali-island','aurora','Aurora','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('amali-island','amorino','Amorino','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('the-world-islands','germany-island','Germany Island','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-world-islands','sweden-palace','Sweden Palace','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('the-world-islands','floating-seahorse','Floating Seahorse','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('rashid-yachts-marina','seascape','Seascape','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('rashid-yachts-marina','sunridge','Sunridge','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('rashid-yachts-marina','sirius','Sirius','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('rashid-yachts-marina','marina-views','Marina Views','offplan','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-creek-harbour','creek-horizon','Creek Horizon','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-creek-harbour','harbour-gate','Harbour Gate','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-creek-harbour','creek-beach','Creek Beach','mixed','Broker-provided master list (validated), Jul 2026.'),
  ('dubai-creek-harbour','creek-waters','Creek Waters','mixed','Broker-provided master list (validated), Jul 2026.')
) as v(comm, slug, name, status, note)
on conflict (community_id, slug) do update set
  name=excluded.name, status=excluded.status,
  data_confidence=excluded.data_confidence, source_note=excluded.source_note;
